// Original bug: KT-31222

data class DataClass(val bytes: ByteArray)

data class FixedDataClass(val bytes: ByteArray) {
    // equals() and hashCode() were generated by IntelliJ

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as FixedDataClass

        if (!bytes.contentEquals(other.bytes)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = bytes.contentHashCode()
        return result
    }
}

fun main() {
    val d1 = DataClass(byteArrayOf(1, 2, 3))
    val d2 = DataClass(byteArrayOf(1, 2, 3))
    println(d1 == d2)

    val f1 = FixedDataClass(byteArrayOf(1, 2, 3))
    val f2 = FixedDataClass(byteArrayOf(1, 2, 3))
    println(f1 == f2)
}
